/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ScheduledPost {
  'status' : string,
  'title' : string,
  'scheduledTime' : bigint,
  'description' : string,
  'platform' : string,
  'projectId' : bigint,
}
export interface SocialAccount { 'platform' : string, 'accountHandle' : string }
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VideoProject {
  'id' : bigint,
  'status' : string,
  'title' : string,
  'owner' : Principal,
  'createdAt' : bigint,
  'description' : string,
  'platform' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addSocialAccount' : ActorMethod<[string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createVideoProject' : ActorMethod<[string, string, string], bigint>,
  'deleteVideoProject' : ActorMethod<[bigint], undefined>,
  'getAllScheduledPosts' : ActorMethod<[], Array<ScheduledPost>>,
  'getAllVideoProjects' : ActorMethod<[], Array<VideoProject>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getScheduledPosts' : ActorMethod<[bigint], Array<ScheduledPost>>,
  'getSocialAccounts' : ActorMethod<[], Array<SocialAccount>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVideoProject' : ActorMethod<[bigint], VideoProject>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'schedulePost' : ActorMethod<
    [bigint, string, bigint, string, string],
    undefined
  >,
  'updatePostStatus' : ActorMethod<[bigint, bigint, string], undefined>,
  'updateVideoProject' : ActorMethod<
    [bigint, string, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];