/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ScheduledPost = IDL.Record({
  'status' : IDL.Text,
  'title' : IDL.Text,
  'scheduledTime' : IDL.Int,
  'description' : IDL.Text,
  'platform' : IDL.Text,
  'projectId' : IDL.Nat,
});
export const VideoProject = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'title' : IDL.Text,
  'owner' : IDL.Principal,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'platform' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const SocialAccount = IDL.Record({
  'platform' : IDL.Text,
  'accountHandle' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addSocialAccount' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createVideoProject' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteVideoProject' : IDL.Func([IDL.Nat], [], []),
  'getAllScheduledPosts' : IDL.Func([], [IDL.Vec(ScheduledPost)], ['query']),
  'getAllVideoProjects' : IDL.Func([], [IDL.Vec(VideoProject)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getScheduledPosts' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ScheduledPost)],
      ['query'],
    ),
  'getSocialAccounts' : IDL.Func([], [IDL.Vec(SocialAccount)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVideoProject' : IDL.Func([IDL.Nat], [VideoProject], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'schedulePost' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Int, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updatePostStatus' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
  'updateVideoProject' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ScheduledPost = IDL.Record({
    'status' : IDL.Text,
    'title' : IDL.Text,
    'scheduledTime' : IDL.Int,
    'description' : IDL.Text,
    'platform' : IDL.Text,
    'projectId' : IDL.Nat,
  });
  const VideoProject = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'title' : IDL.Text,
    'owner' : IDL.Principal,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'platform' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const SocialAccount = IDL.Record({
    'platform' : IDL.Text,
    'accountHandle' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addSocialAccount' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createVideoProject' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteVideoProject' : IDL.Func([IDL.Nat], [], []),
    'getAllScheduledPosts' : IDL.Func([], [IDL.Vec(ScheduledPost)], ['query']),
    'getAllVideoProjects' : IDL.Func([], [IDL.Vec(VideoProject)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getScheduledPosts' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ScheduledPost)],
        ['query'],
      ),
    'getSocialAccounts' : IDL.Func([], [IDL.Vec(SocialAccount)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVideoProject' : IDL.Func([IDL.Nat], [VideoProject], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'schedulePost' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Int, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updatePostStatus' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
    'updateVideoProject' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };